services:
  postgres:
    image: postgres:16
    container_name: owasp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: owaspdb
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
